### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/usdata#1]
Add @ldorazio to authors in next release for her contributions for gathering the county data

**Comment by mine-cetinkaya-rundel** [comment]
@ldorazio Which email address should I use? And do you have an ORCID id you want to add?

**Comment by ldorazio** [comment]
Hi Mine,
I use this one:  leah.dorazio@sfuhs.org<mailto:leah.dorazio@sfuhs.org>

I don’t have an ORCID.

Thanks!
Leah
